import type { VoiceExpression, VoiceLine } from './voice-lines.js'
import { lineId } from './voice-lines.js'

function line(
  personalityId: string,
  event: VoiceLine['event'],
  index: number,
  text: string,
  weight: number,
  expression: VoiceExpression | null = null,
): VoiceLine {
  return {
    id: lineId(personalityId, event, index),
    personalityId,
    event,
    text,
    expression,
    weight,
  }
}

export const VOICE_PACK: readonly VoiceLine[] = [
  // Albie - silent rookie, lowest tilt resistance, comes apart on bad beats.
  line('albie', 'win_big', 0, '', 3, 'breath'),
  line('albie', 'win_big', 1, 'Alright then.', 1),
  line('albie', 'win_small', 0, '', 3, 'breath'),
  line('albie', 'win_small', 1, 'Okay.', 1),
  line('albie', 'lose_big', 0, '', 3, 'sigh'),
  line('albie', 'lose_big', 1, 'Ah, that was bad.', 1),
  line('albie', 'lose_small', 0, '', 3, 'sigh'),
  line('albie', 'lose_small', 1, 'Hm.', 1),
  line('albie', 'bluff_caught', 0, '', 3, 'sigh'),
  line('albie', 'bluff_caught', 1, 'Told you nothing.', 1),
  line('albie', 'fold_pressured', 0, '', 3, 'breath'),
  line('albie', 'fold_pressured', 1, 'Fine, I fold.', 1),
  line('albie', 'all_in', 0, '', 3, 'breath'),
  line('albie', 'all_in', 1, 'All in then.', 1),
  line('albie', 'raise', 0, '', 3, 'breath'),
  line('albie', 'raise', 1, 'I raise.', 1),
  line('albie', 'bad_beat', 0, '', 3, 'groan'),
  line('albie', 'bad_beat', 1, 'Unbelievable.', 1),
  line('albie', 'greeting', 0, '', 3, 'breath'),
  line('albie', 'greeting', 1, 'Hello everyone.', 1),
  line('albie', 'idle_banter', 0, '', 3, 'breath'),
  line('albie', 'idle_banter', 1, 'Nice table.', 1),
  line('albie', 'opponent_stalling', 0, '', 3, 'sigh'),
  line('albie', 'opponent_stalling', 1, 'Take your time.', 1),

  // Doyle - silent rookie, quiet and steady.
  line('doyle', 'win_big', 0, '', 3, 'breath'),
  line('doyle', 'win_big', 1, 'That works.', 1),
  line('doyle', 'win_small', 0, '', 3, 'breath'),
  line('doyle', 'win_small', 1, 'Good.', 1),
  line('doyle', 'lose_big', 0, '', 3, 'sigh'),
  line('doyle', 'lose_big', 1, 'Now that stings.', 1),
  line('doyle', 'lose_small', 0, '', 3, 'sigh'),
  line('doyle', 'lose_small', 1, 'Mmm.', 1),
  line('doyle', 'bluff_caught', 0, '', 3, 'scoff'),
  line('doyle', 'bluff_caught', 1, 'Ah, you got me.', 1),
  line('doyle', 'fold_pressured', 0, '', 3, 'breath'),
  line('doyle', 'fold_pressured', 1, 'Fine, out.', 1),
  line('doyle', 'all_in', 0, '', 3, 'breath'),
  line('doyle', 'all_in', 1, 'All in.', 1),
  line('doyle', 'raise', 0, '', 3, 'breath'),
  line('doyle', 'raise', 1, 'Make it a raise.', 1),
  line('doyle', 'bad_beat', 0, '', 3, 'groan'),
  line('doyle', 'bad_beat', 1, 'That got away.', 1),
  line('doyle', 'greeting', 0, '', 3, 'breath'),
  line('doyle', 'greeting', 1, 'Good evening all.', 1),
  line('doyle', 'idle_banter', 0, '', 3, 'breath'),
  line('doyle', 'idle_banter', 1, 'Quiet round.', 1),
  line('doyle', 'opponent_stalling', 0, '', 3, 'sigh'),
  line('doyle', 'opponent_stalling', 1, 'Whenever you are ready.', 1),

  // Gordo - silent novice, aggressive but speaks little.
  line('gordo', 'win_big', 0, '', 3, 'scoff'),
  line('gordo', 'win_big', 1, 'Obviously.', 1),
  line('gordo', 'win_small', 0, '', 3, 'scoff'),
  line('gordo', 'win_small', 1, 'Fine.', 1),
  line('gordo', 'lose_big', 0, '', 3, 'groan'),
  line('gordo', 'lose_big', 1, 'I wanted that.', 1),
  line('gordo', 'lose_small', 0, '', 3, 'scoff'),
  line('gordo', 'lose_small', 1, 'Whatever.', 1),
  line('gordo', 'bluff_caught', 0, '', 3, 'laugh'),
  line('gordo', 'bluff_caught', 1, 'Called it, chump.', 1),
  line('gordo', 'fold_pressured', 0, '', 3, 'scoff'),
  line('gordo', 'fold_pressured', 1, 'I am out anyway.', 1),
  line('gordo', 'all_in', 0, '', 3, 'scoff'),
  line('gordo', 'all_in', 1, 'Push it all in.', 1),
  line('gordo', 'raise', 0, '', 3, 'scoff'),
  line('gordo', 'raise', 1, 'Bump you.', 1),
  line('gordo', 'bad_beat', 0, '', 3, 'groan'),
  line('gordo', 'bad_beat', 1, 'Robbed on the river.', 1),
  line('gordo', 'greeting', 0, '', 3, 'scoff'),
  line('gordo', 'greeting', 1, 'Evening.', 1),
  line('gordo', 'idle_banter', 0, '', 3, 'scoff'),
  line('gordo', 'idle_banter', 1, 'This table is slow.', 1),
  line('gordo', 'opponent_stalling', 0, '', 3, 'tut'),
  line('gordo', 'opponent_stalling', 1, 'Move it along.', 1),

  // Jules - silent og, aggressive and cold, near unshakeable.
  line('jules', 'win_big', 0, '', 3, 'breath'),
  line('jules', 'win_big', 1, 'Nothing to it.', 1),
  line('jules', 'win_small', 0, '', 3, 'breath'),
  line('jules', 'win_small', 1, 'Fine.', 1),
  line('jules', 'lose_big', 0, '', 3, 'sigh'),
  line('jules', 'lose_big', 1, 'I will get it back.', 1),
  line('jules', 'lose_small', 0, '', 3, 'breath'),
  line('jules', 'lose_small', 1, 'Mm.', 1),
  line('jules', 'bluff_caught', 0, '', 3, 'scoff'),
  line('jules', 'bluff_caught', 1, 'You guessed, fine.', 1),
  line('jules', 'fold_pressured', 0, '', 3, 'breath'),
  line('jules', 'fold_pressured', 1, 'Out. Next hand.', 1),
  line('jules', 'all_in', 0, '', 3, 'breath'),
  line('jules', 'all_in', 1, 'Everything in.', 1),
  line('jules', 'raise', 0, '', 3, 'breath'),
  line('jules', 'raise', 1, 'Raising.', 1),
  line('jules', 'bad_beat', 0, '', 3, 'sigh'),
  line('jules', 'bad_beat', 1, 'Seen worse.', 1),
  line('jules', 'greeting', 0, '', 3, 'breath'),
  line('jules', 'greeting', 1, 'Alright.', 1),
  line('jules', 'idle_banter', 0, '', 3, 'breath'),
  line('jules', 'idle_banter', 1, 'Deal them.', 1),
  line('jules', 'opponent_stalling', 0, '', 3, 'scoff'),
  line('jules', 'opponent_stalling', 1, 'Decide already.', 1),

  // Clem - occasional rookie, tight, cautious.
  line('clem', 'win_big', 0, 'Well now, would you look at that.', 3, 'laugh'),
  line('clem', 'win_big', 1, 'That hand played itself.', 1),
  line('clem', 'win_big', 2, 'Plenty more where that came from.', 1),
  line('clem', 'win_small', 0, 'Ah, small score.', 3, 'cheer'),
  line('clem', 'win_small', 1, 'Happy with that.', 1),
  line('clem', 'win_small', 2, 'Every little helps.', 1),
  line('clem', 'lose_big', 0, 'Well that hurt a bit.', 3, 'groan'),
  line('clem', 'lose_big', 1, 'I misread that one.', 1),
  line('clem', 'lose_big', 2, 'Back to patient play.', 1),
  line('clem', 'lose_small', 0, 'Hm, fine.', 3, 'sigh'),
  line('clem', 'lose_small', 1, 'Could have been worse.', 1),
  line('clem', 'lose_small', 2, 'Move along now.', 1),
  line('clem', 'bluff_caught', 0, 'Ah, you saw through me.', 3, 'scoff'),
  line('clem', 'bluff_caught', 1, 'That bluff was thin anyway.', 1),
  line('clem', 'bluff_caught', 2, 'I will not try that again.', 1),
  line('clem', 'fold_pressured', 0, 'Right, I am folding.', 3, 'breath'),
  line('clem', 'fold_pressured', 1, 'Too rich for me.', 1),
  line('clem', 'fold_pressured', 2, 'I will live to fold again.', 1),
  line('clem', 'all_in', 0, 'Going all in, here we go.', 3, 'breath'),
  line('clem', 'all_in', 1, 'Everything in the middle.', 1),
  line('clem', 'all_in', 2, 'All or nothing then.', 1),
  line('clem', 'raise', 0, 'I am going to raise.', 3, 'breath'),
  line('clem', 'raise', 1, 'Bumping it up some.', 1),
  line('clem', 'raise', 2, 'A raise from me.', 1),
  line('clem', 'bad_beat', 0, 'Oh, beaten on the last card.', 3, 'groan'),
  line('clem', 'bad_beat', 1, 'That is a rough run-out.', 1),
  line('clem', 'bad_beat', 2, 'Nothing I could do there.', 1),
  line('clem', 'greeting', 0, 'Hello, good to be here.', 3, 'cheer'),
  line('clem', 'greeting', 1, 'Evening, all.', 1),
  line('clem', 'greeting', 2, 'Nice to meet you lot.', 1),
  line('clem', 'idle_banter', 0, 'Has anyone seen the rain out back?', 3, 'breath'),
  line('clem', 'idle_banter', 1, 'Good weather for poker.', 1),
  line('clem', 'idle_banter', 2, 'Tasty coffee they keep here.', 1),
  line('clem', 'opponent_stalling', 0, 'Take your time, I have all night.', 3, 'breath'),
  line('clem', 'opponent_stalling', 1, 'No rush on my side.', 1),
  line('clem', 'opponent_stalling', 2, 'Whenever you are ready.', 1),

  // Edna - occasional novice, aggressive, enjoys the contest.
  line('edna', 'win_big', 0, 'Ha, that was easy.', 3, 'cheer'),
  line('edna', 'win_big', 1, 'I do like it when you call.', 1),
  line('edna', 'win_big', 2, 'Nice pot, thank you kindly.', 1),
  line('edna', 'win_small', 0, 'Oh, pocket money.', 3, 'cheer'),
  line('edna', 'win_small', 1, 'I will take that.', 1),
  line('edna', 'win_small', 2, 'Small but welcome.', 1),
  line('edna', 'lose_big', 0, 'Well, that is gone.', 3, 'groan'),
  line('edna', 'lose_big', 1, 'You outplayed me there.', 1),
  line('edna', 'lose_big', 2, 'I will be back for it.', 1),
  line('edna', 'lose_small', 0, 'Hmph, your win.', 3, 'sigh'),
  line('edna', 'lose_small', 1, 'Counts, I suppose.', 1),
  line('edna', 'lose_small', 2, 'Fine, next hand wins.', 1),
  line('edna', 'bluff_caught', 0, 'Caught, well played.', 3, 'laugh'),
  line('edna', 'bluff_caught', 1, 'You read me like a book.', 1),
  line('edna', 'bluff_caught', 2, 'Ah, I played that wrong.', 1),
  line('edna', 'fold_pressured', 0, 'Right, folding to you.', 3, 'breath'),
  line('edna', 'fold_pressured', 1, 'I know when to quit.', 1),
  line('edna', 'fold_pressured', 2, 'Out, but mark my words.', 1),
  line('edna', 'all_in', 0, 'All in, I am feeling brave.', 3, 'cheer'),
  line('edna', 'all_in', 1, 'Everything on the line.', 1),
  line('edna', 'all_in', 2, 'Let us see whose luck it is.', 1),
  line('edna', 'raise', 0, 'Raise, I am in a mood.', 3, 'scoff'),
  line('edna', 'raise', 1, 'Bumping the betting up.', 1),
  line('edna', 'raise', 2, 'That will cost you.', 1),
  line('edna', 'bad_beat', 0, 'Oh now that is cruel.', 3, 'groan'),
  line('edna', 'bad_beat', 1, 'Outdrawn on the very last.', 1),
  line('edna', 'bad_beat', 2, 'The cards have no mercy.', 1),
  line('edna', 'greeting', 0, 'Evening, darlings.', 3, 'cheer'),
  line('edna', 'greeting', 1, 'Hello all, good table.', 1),
  line('edna', 'greeting', 2, 'Right, let us begin.', 1),
  line('edna', 'idle_banter', 0, 'Anyone else want a drink?', 3, 'cheer'),
  line('edna', 'idle_banter', 1, 'The rooftop wind is brisk.', 1),
  line('edna', 'idle_banter', 2, 'I do enjoy a good table.', 1),
  line('edna', 'opponent_stalling', 0, 'Come on, the night is short.', 3, 'tut'),
  line('edna', 'opponent_stalling', 1, 'Decide, I am waiting.', 1),
  line('edna', 'opponent_stalling', 2, 'No hurry, then again hurry.', 1),

  // Irving - occasional novice, tight and precise, calm.
  line('irving', 'win_big', 0, 'A clean hand, well taken.', 3, 'cheer'),
  line('irving', 'win_big', 1, 'The math favored me there.', 1),
  line('irving', 'win_big', 2, 'Capital, that rounds off nicely.', 1),
  line('irving', 'win_small', 0, 'Modest, but counted.', 3, 'breath'),
  line('irving', 'win_small', 1, 'Every win adds up.', 1),
  line('irving', 'win_small', 2, 'Pleased with that one.', 1),
  line('irving', 'lose_big', 0, 'A costly misstep.', 3, 'sigh'),
  line('irving', 'lose_big', 1, 'I miscalculated the odds.', 1),
  line('irving', 'lose_big', 2, 'I will review that hand.', 1),
  line('irving', 'lose_small', 0, 'A minor setback.', 3, 'breath'),
  line('irving', 'lose_small', 1, 'Acceptable losses.', 1),
  line('irving', 'lose_small', 2, 'I was behind anyway.', 1),
  line('irving', 'bluff_caught', 0, 'Detected, a fine read.', 3, 'scoff'),
  line('irving', 'bluff_caught', 1, 'My bluff was seen through.', 1),
  line('irving', 'bluff_caught', 2, 'That plan failed neatly.', 1),
  line('irving', 'fold_pressured', 0, 'I concede this hand.', 3, 'breath'),
  line('irving', 'fold_pressured', 1, 'Folding is the disciplined move.', 1),
  line('irving', 'fold_pressured', 2, 'I will not chase it.', 1),
  line('irving', 'all_in', 0, 'I put it all in.', 3, 'breath'),
  line('irving', 'all_in', 1, 'Every chip on this one.', 1),
  line('irving', 'all_in', 2, 'The math says all in.', 1),
  line('irving', 'raise', 0, 'I raise, modestly.', 3, 'breath'),
  line('irving', 'raise', 1, 'Bumping the stakes up.', 1),
  line('irving', 'raise', 2, 'A measured raise.', 1),
  line('irving', 'bad_beat', 0, 'A textbook bad beat.', 3, 'sigh'),
  line('irving', 'bad_beat', 1, 'The odds did not hold.', 1),
  line('irving', 'bad_beat', 2, 'Variance in its glory.', 1),
  line('irving', 'greeting', 0, 'Good evening, everyone.', 3, 'cheer'),
  line('irving', 'greeting', 1, 'Hello, I am Irving.', 1),
  line('irving', 'greeting', 2, 'Pleasure to join the table.', 1),
  line('irving', 'idle_banter', 0, 'The pot odds favor patience.', 3, 'breath'),
  line('irving', 'idle_banter', 1, 'This suite is rather grand.', 1),
  line('irving', 'idle_banter', 2, 'Quiet is good here.', 1),
  line('irving', 'opponent_stalling', 0, 'Absolutely no rush.', 3, 'breath'),
  line('irving', 'opponent_stalling', 1, 'Consider your options well.', 1),
  line('irving', 'opponent_stalling', 2, 'A careful player, good.', 1),

  // Kazimir - occasional og, calm and wise, high bluff rate, unshakeable.
  line('kazimir', 'win_big', 0, 'The old hand reads still work.', 3, 'cheer'),
  line('kazimir', 'win_big', 1, 'I have seen this before.', 1),
  line('kazimir', 'win_big', 2, 'Fortune favors the patient.', 1),
  line('kazimir', 'win_small', 0, 'A small harvest.', 3, 'breath'),
  line('kazimir', 'win_small', 1, 'Every chip is earned.', 1),
  line('kazimir', 'win_small', 2, 'Enough to keep moving.', 1),
  line('kazimir', 'lose_big', 0, 'I let that one go cheaply.', 3, 'sigh'),
  line('kazimir', 'lose_big', 1, 'The river owed me, maybe not.', 1),
  line('kazimir', 'lose_big', 2, 'A mountaintop, a valley.', 1),
  line('kazimir', 'lose_small', 0, 'A trickle away, fine.', 3, 'breath'),
  line('kazimir', 'lose_small', 1, 'These things come and go.', 1),
  line('kazimir', 'lose_small', 2, 'I pay my dues.', 1),
  line('kazimir', 'bluff_caught', 0, 'Ah, you smoke me out.', 3, 'laugh'),
  line('kazimir', 'bluff_caught', 1, 'Bluffing is an art, tonight lost.', 1),
  line('kazimir', 'bluff_caught', 2, 'I tip my hat there.', 1),
  line('kazimir', 'fold_pressured', 0, 'I fold, the story ends.', 3, 'breath'),
  line('kazimir', 'fold_pressured', 1, 'Discretion wins the war.', 1),
  line('kazimir', 'fold_pressured', 2, 'Another day, another hand.', 1),
  line('kazimir', 'all_in', 0, 'All in, a leap of faith.', 3, 'breath'),
  line('kazimir', 'all_in', 1, 'Everything rides on this.', 1),
  line('kazimir', 'all_in', 2, 'The fates decide now.', 1),
  line('kazimir', 'raise', 0, 'A raise, to test you.', 3, 'scoff'),
  line('kazimir', 'raise', 1, 'I push the betting up.', 1),
  line('kazimir', 'raise', 2, 'That will separate us.', 1),
  line('kazimir', 'bad_beat', 0, 'The cards turn against me.', 3, 'sigh'),
  line('kazimir', 'bad_beat', 1, 'I have survived worse.', 1),
  line('kazimir', 'bad_beat', 2, 'Variance is my oldest enemy.', 1),
  line('kazimir', 'greeting', 0, 'Good evening, my friends.', 3, 'cheer'),
  line('kazimir', 'greeting', 1, 'Welcome to the felt.', 1),
  line('kazimir', 'greeting', 2, 'Let us play some cards.', 1),
  line('kazimir', 'idle_banter', 0, 'The night is young at least.', 3, 'breath'),
  line('kazimir', 'idle_banter', 1, 'This room has some soul.', 1),
  line('kazimir', 'idle_banter', 2, 'A good table, finally.', 1),
  line('kazimir', 'opponent_stalling', 0, 'Patience, take your time.', 3, 'breath'),
  line('kazimir', 'opponent_stalling', 1, 'A considered choice is best.', 1),
  line('kazimir', 'opponent_stalling', 2, 'I am not going anywhere.', 1),

  // Bernadette - constant rookie, chatty and warm, slight bluffer.
  line('bernadette', 'win_big', 0, 'Oh lovely, look at that stack.', 3, 'cheer'),
  line('bernadette', 'win_big', 1, 'That was a good call after all.', 1),
  line('bernadette', 'win_big', 2, 'I am on a roll tonight.', 1),
  line('bernadette', 'win_big', 3, 'Watch out, I have figured it out.', 1),
  line('bernadette', 'win_small', 0, 'A little win, how nice.', 3, 'cheer'),
  line('bernadette', 'win_small', 1, 'Every chip counts for me.', 1),
  line('bernadette', 'win_small', 2, 'Oh good, that helps.', 1),
  line('bernadette', 'win_small', 3, 'I will take whatever comes.', 1),
  line('bernadette', 'lose_big', 0, 'Oh no, that was my stack.', 3, 'groan'),
  line('bernadette', 'lose_big', 1, 'I really liked that hand too.', 1),
  line('bernadette', 'lose_big', 2, 'Back down to earth then.', 1),
  line('bernadette', 'lose_big', 3, 'Well, that did not go my way.', 1),
  line('bernadette', 'lose_small', 0, 'Ah, a small loss, fine.', 3, 'sigh'),
  line('bernadette', 'lose_small', 1, 'I will win it back next.', 1),
  line('bernadette', 'lose_small', 2, 'No harm done really.', 1),
  line('bernadette', 'lose_small', 3, 'That one was close.', 1),
  line('bernadette', 'bluff_caught', 0, 'Oh you got me that time.', 3, 'laugh'),
  line('bernadette', 'bluff_caught', 1, 'I swear I had nothing there.', 1),
  line('bernadette', 'bluff_caught', 2, 'Caught red handed again.', 1),
  line('bernadette', 'bluff_caught', 3, 'You are too sharp for me.', 1),
  line('bernadette', 'fold_pressured', 0, 'Right, I am folding, scary pot.', 3, 'breath'),
  line('bernadette', 'fold_pressured', 1, 'I do not like my chances.', 1),
  line('bernadette', 'fold_pressured', 2, 'Too rich for me today.', 1),
  line('bernadette', 'fold_pressured', 3, 'Folding and not looking back.', 1),
  line('bernadette', 'all_in', 0, 'Everything in, fingers crossed.', 3, 'breath'),
  line('bernadette', 'all_in', 1, 'I am all in now, lucky me.', 1),
  line('bernadette', 'all_in', 2, 'Here goes nothing at all.', 1),
  line('bernadette', 'all_in', 3, 'All my chips are in.', 1),
  line('bernadette', 'raise', 0, 'I am going to raise you.', 3, 'scoff'),
  line('bernadette', 'raise', 1, 'Bumping right up there.', 1),
  line('bernadette', 'raise', 2, 'Make it interesting then.', 1),
  line('bernadette', 'raise', 3, 'A healthy raise from me.', 1),
  line('bernadette', 'bad_beat', 0, 'Oh my cards broke my heart.', 3, 'groan'),
  line('bernadette', 'bad_beat', 1, 'That last card was so cruel.', 1),
  line('bernadette', 'bad_beat', 2, 'I was winning right until there.', 1),
  line('bernadette', 'bad_beat', 3, 'What a way to lose a hand.', 1),
  line('bernadette', 'greeting', 0, 'Hello everyone, how lovely.', 3, 'cheer'),
  line('bernadette', 'greeting', 1, 'Good to see you all again.', 1),
  line('bernadette', 'greeting', 2, 'I am ready for some fun.', 1),
  line('bernadette', 'greeting', 3, 'Evening, this is a nice table.', 1),
  line('bernadette', 'idle_banter', 0, 'Has anyone been to the rooftop bar?', 3, 'cheer'),
  line('bernadette', 'idle_banter', 1, 'I love the music in here.', 1),
  line('bernadette', 'idle_banter', 2, 'What a beautiful venue tonight.', 1),
  line('bernadette', 'idle_banter', 3, 'This is the best seat in town.', 1),
  line('bernadette', 'opponent_stalling', 0, 'Come on now, I am waiting.', 3, 'tut'),
  line('bernadette', 'opponent_stalling', 1, 'I do not have all night.', 1),
  line('bernadette', 'opponent_stalling', 2, 'Alright, whenever you are ready.', 1),
  line('bernadette', 'opponent_stalling', 3, 'Tick tock, my patience wears thin.', 1),

  // Frank - constant novice, steady grinder, resilient.
  line('frank', 'win_big', 0, 'And that is how it is done.', 3, 'cheer'),
  line('frank', 'win_big', 1, 'Solid hand, solid result.', 1),
  line('frank', 'win_big', 2, 'The grinder eats again.', 1),
  line('frank', 'win_big', 3, 'Money in, money out, profit.', 1),
  line('frank', 'win_small', 0, 'Tidy little win there.', 3, 'cheer'),
  line('frank', 'win_small', 1, 'I will bank that one.', 1),
  line('frank', 'win_small', 2, 'Steady is the way.', 1),
  line('frank', 'win_small', 3, 'Good enough for me.', 1),
  line('frank', 'lose_big', 0, 'That one cost me some sleep.', 3, 'groan'),
  line('frank', 'lose_big', 1, 'You win some, you lose some.', 1),
  line('frank', 'lose_big', 2, 'Time to tighten the grip.', 1),
  line('frank', 'lose_big', 3, 'That is how the cards go.', 1),
  line('frank', 'lose_small', 0, 'Small dent, nothing more.', 3, 'sigh'),
  line('frank', 'lose_small', 1, 'I will recover it shortly.', 1),
  line('frank', 'lose_small', 2, 'Standard stuff really.', 1),
  line('frank', 'lose_small', 3, 'Shake it off and move on.', 1),
  line('frank', 'bluff_caught', 0, 'Ah, my bluff backfired.', 3, 'scoff'),
  line('frank', 'bluff_caught', 1, 'Caught out, that is poker.', 1),
  line('frank', 'bluff_caught', 2, 'I took a shot, missed.', 1),
  line('frank', 'bluff_caught', 3, 'Respect for that call there.', 1),
  line('frank', 'fold_pressured', 0, 'I am out of this one.', 3, 'breath'),
  line('frank', 'fold_pressured', 1, 'Wisdom says fold it.', 1),
  line('frank', 'fold_pressured', 2, 'No point chasing that.', 1),
  line('frank', 'fold_pressured', 3, 'Discipline again, I fold.', 1),
  line('frank', 'all_in', 0, 'All in, everything follows.', 3, 'breath'),
  line('frank', 'all_in', 1, 'My whole stack is at stake.', 1),
  line('frank', 'all_in', 2, 'Time to commit fully.', 1),
  line('frank', 'all_in', 3, 'All or nothing, and now done.', 1),
  line('frank', 'raise', 0, 'I am raising this pot.', 3, 'scoff'),
  line('frank', 'raise', 1, 'Bumping it straight up.', 1),
  line('frank', 'raise', 2, 'Let us make it cost more.', 1),
  line('frank', 'raise', 3, 'A raise to sort you out.', 1),
  line('frank', 'bad_beat', 0, 'Outdrawn again, such is life.', 3, 'sigh'),
  line('frank', 'bad_beat', 1, 'The river had other plans.', 1),
  line('frank', 'bad_beat', 2, 'I made the right play too.', 1),
  line('frank', 'bad_beat', 3, 'Variance does not respect skill.', 1),
  line('frank', 'greeting', 0, 'Evening everyone, good to be here.', 3, 'cheer'),
  line('frank', 'greeting', 1, 'Hello, Frank is at the table.', 1),
  line('frank', 'greeting', 2, 'Good table, good company.', 1),
  line('frank', 'greeting', 3, 'Let us have a clean game.', 1),
  line('frank', 'idle_banter', 0, 'Anyone fancy another round?', 3, 'cheer'),
  line('frank', 'idle_banter', 1, 'This suite has good lighting.', 1),
  line('frank', 'idle_banter', 2, 'I always like the rooftop crowd.', 1),
  line('frank', 'idle_banter', 3, 'A quiet table suits me fine.', 1),
  line('frank', 'opponent_stalling', 0, 'Take your time, no worries.', 3, 'breath'),
  line('frank', 'opponent_stalling', 1, 'I am as patient as they come.', 1),
  line('frank', 'opponent_stalling', 2, 'Whenever you are settled.', 1),
  line('frank', 'opponent_stalling', 3, 'Careful thought beats rushing.', 1),

  // Hyacinth - constant novice, proud and sharp, needle on the table.
  line('hyacinth', 'win_big', 0, 'As expected, of course it is mine.', 3, 'cheer'),
  line('hyacinth', 'win_big', 1, 'I do hate to gloat, but well done me.', 1),
  line('hyacinth', 'win_big', 2, 'That hand was clearly mine all along.', 1),
  line('hyacinth', 'win_big', 3, 'Another pot to the best player here.', 1),
  line('hyacinth', 'win_small', 0, 'A modest sum, but it is mine.', 3, 'cheer'),
  line('hyacinth', 'win_small', 1, 'Even little pots count to me.', 1),
  line('hyacinth', 'win_small', 2, 'I shall take that, thank you.', 1),
  line('hyacinth', 'win_small', 3, 'You all let that one go freely.', 1),
  line('hyacinth', 'lose_big', 0, 'I was robbed, simply robbed.', 3, 'groan'),
  line('hyacinth', 'lose_big', 1, 'That result is simply not acceptable.', 1),
  line('hyacinth', 'lose_big', 2, 'You got lucky, nothing more.', 1),
  line('hyacinth', 'lose_big', 3, 'I refuse to accept that outcome.', 1),
  line('hyacinth', 'lose_small', 0, 'A trifle, hardly worth mentioning.', 3, 'sigh'),
  line('hyacinth', 'lose_small', 1, 'I have far better days ahead.', 1),
  line('hyacinth', 'lose_small', 2, 'Do not let that worry you.', 1),
  line('hyacinth', 'lose_small', 3, 'A tiny setback, quickly fixed.', 1),
  line('hyacinth', 'bluff_caught', 0, 'You caught me? Outrageous.', 3, 'scoff'),
  line('hyacinth', 'bluff_caught', 1, 'I had you perfectly read, I think not.', 1),
  line('hyacinth', 'bluff_caught', 2, 'Well, that plan failed utterly.', 1),
  line('hyacinth', 'bluff_caught', 3, 'I shall never admit to bluffing.', 1),
  line('hyacinth', 'fold_pressured', 0, 'Fine, I fold, but I am watching.', 3, 'breath'),
  line('hyacinth', 'fold_pressured', 1, 'I bow out of this particular round.', 1),
  line('hyacinth', 'fold_pressured', 2, 'Not worth my precious chips.', 1),
  line('hyacinth', 'fold_pressured', 3, 'Fold, and judge you all fairly.', 1),
  line('hyacinth', 'all_in', 0, 'All in, and not a penny less.', 3, 'breath'),
  line('hyacinth', 'all_in', 1, 'Everything I own goes forward now.', 1),
  line('hyacinth', 'all_in', 2, 'I commit my whole fortune here.', 1),
  line('hyacinth', 'all_in', 3, 'Watch closely, this is my moment.', 1),
  line('hyacinth', 'raise', 0, 'I raise, and expect respect.', 3, 'scoff'),
  line('hyacinth', 'raise', 1, 'Bumping the stakes up, naturally.', 1),
  line('hyacinth', 'raise', 2, 'That will separate the casual player.', 1),
  line('hyacinth', 'raise', 3, 'My raise, how delightful.', 1),
  line('hyacinth', 'bad_beat', 0, 'Outdrawn? This is a scandal.', 3, 'groan'),
  line('hyacinth', 'bad_beat', 1, 'The last card betrayed me personally.', 1),
  line('hyacinth', 'bad_beat', 2, 'I will not be beaten so cheaply.', 1),
  line('hyacinth', 'bad_beat', 3, 'That river card is a travesty.', 1),
  line('hyacinth', 'greeting', 0, 'Ah, good evening, everyone.', 3, 'cheer'),
  line('hyacinth', 'greeting', 1, 'How lovely to see such a fine table.', 1),
  line('hyacinth', 'greeting', 2, 'I do hope you all brought your best.', 1),
  line('hyacinth', 'greeting', 3, 'Settle in, the master has arrived.', 1),
  line('hyacinth', 'idle_banter', 0, 'This suite is rather beneath my taste.', 3, 'scoff'),
  line('hyacinth', 'idle_banter', 1, 'One does try to enjoy the company.', 1),
  line('hyacinth', 'idle_banter', 2, 'The cocktails here are passable at best.', 1),
  line('hyacinth', 'idle_banter', 3, 'I am simply too good for most of you.', 1),
  line('hyacinth', 'opponent_stalling', 0, 'Do hurry, I have a schedule.', 3, 'tut'),
  line('hyacinth', 'opponent_stalling', 1, 'Your hesitation is tiresome.', 1),
  line('hyacinth', 'opponent_stalling', 2, 'Must you take so very long?', 1),
  line('hyacinth', 'opponent_stalling', 3, 'I have not got all evening, if you please.', 1),

  // Lilah - constant og, loudest player, aggressive and risky.
  line('lilah', 'win_big', 0, 'Ha, chewed you all up.', 3, 'cheer'),
  line('lilah', 'win_big', 1, 'Yeah, that is how it is done.', 1),
  line('lilah', 'win_big', 2, 'I play this game my way.', 1),
  line('lilah', 'win_big', 3, 'Pay the loudest player at the table.', 1),
  line('lilah', 'win_small', 0, 'Eh, chicken feed, but taken.', 3, 'cheer'),
  line('lilah', 'win_small', 1, 'A win is a win is a win.', 1),
  line('lilah', 'win_small', 2, 'I will fatten this up later.', 1),
  line('lilah', 'win_small', 3, 'Now the real money starts.', 1),
  line('lilah', 'lose_big', 0, 'Whatever, I will bomb you back.', 3, 'scoff'),
  line('lilah', 'lose_big', 1, 'You took one, I take the rest.', 1),
  line('lilah', 'lose_big', 2, 'Do not get used to winning.', 1),
  line('lilah', 'lose_big', 3, 'That was borrowed chips anyway.', 1),
  line('lilah', 'lose_small', 0, 'Pfft, pocket change.', 3, 'scoff'),
  line('lilah', 'lose_small', 1, 'I am not even sweating it.', 1),
  line('lilah', 'lose_small', 2, 'Call that a loss? Nothing.', 1),
  line('lilah', 'lose_small', 3, 'I lost more buying drinks.', 1),
  line('lilah', 'bluff_caught', 0, 'Called my bluff, well well.', 3, 'laugh'),
  line('lilah', 'bluff_caught', 1, 'I bluff and I admit it freely.', 1),
  line('lilah', 'bluff_caught', 2, 'You got lucky, nothing more.', 1),
  line('lilah', 'bluff_caught', 3, 'Bluffing is half my game honestly.', 1),
  line('lilah', 'fold_pressured', 0, 'Fine, I fold, but only here.', 3, 'breath'),
  line('lilah', 'fold_pressured', 1, 'Save it for the big pot.', 1),
  line('lilah', 'fold_pressured', 2, 'Not worth my time or chips.', 1),
  line('lilah', 'fold_pressured', 3, 'I will be back and then some.', 1),
  line('lilah', 'all_in', 0, 'All in, let us see whose nerve', 3, 'cheer'),
  line('lilah', 'all_in', 1, 'Everything I got is in front now.', 1),
  line('lilah', 'all_in', 2, 'Balls deep, that is my style.', 1),
  line('lilah', 'all_in', 3, 'All in and I am not blinking.', 1),
  line('lilah', 'raise', 0, 'Raise, big and bold.', 3, 'scoff'),
  line('lilah', 'raise', 1, 'Bumping it up, naturally.', 1),
  line('lilah', 'raise', 2, 'Time to make you pay to look.', 1),
  line('lilah', 'raise', 3, 'My raise, no weak hearts here.', 1),
  line('lilah', 'bad_beat', 0, 'Ugh, got outdrawn by chance.', 3, 'groan'),
  line('lilah', 'bad_beat', 1, 'Whatever, luck is luck here.', 1),
  line('lilah', 'bad_beat', 2, 'I will steam right over this.', 1),
  line('lilah', 'bad_beat', 3, 'Bad beat, big deal, next hand.', 1),
  line('lilah', 'greeting', 0, 'Hey, the loud one is here.', 3, 'cheer'),
  line('lilah', 'greeting', 1, 'Evening, time for some action.', 1),
  line('lilah', 'greeting', 2, 'Ready to light this table up.', 1),
  line('lilah', 'greeting', 3, 'Hope you brought thick skin tonight.', 1),
  line('lilah', 'idle_banter', 0, 'This table better keep up with me.', 3, 'scoff'),
  line('lilah', 'idle_banter', 1, 'I will say it plainly, play faster.', 1),
  line('lilah', 'idle_banter', 2, 'Anyone else feeling lucky here?', 1),
  line('lilah', 'idle_banter', 3, 'These rookies need some schooling.', 1),
  line('lilah', 'opponent_stalling', 0, 'Hurry up, I am losing interest.', 3, 'tut'),
  line('lilah', 'opponent_stalling', 1, 'Make a move, clock is running.', 1),
  line('lilah', 'opponent_stalling', 2, 'Decide already, I am bored.', 1),
  line('lilah', 'opponent_stalling', 3, 'Think fast or fold fast.', 1),

  // Mickey - constant og, highest tilt resistance, unshakeable, shrugs it off.
  line('mickey', 'win_big', 0, 'There it is, easy pickings.', 3, 'cheer'),
  line('mickey', 'win_big', 1, 'I have done this a thousand times.', 1),
  line('mickey', 'win_big', 2, 'The old dog knows when to bite.', 1),
  line('mickey', 'win_big', 3, 'Money follows those who stay calm.', 1),
  line('mickey', 'win_small', 0, 'A small taste, fine with me.', 3, 'cheer'),
  line('mickey', 'win_small', 1, 'Cha-ching, even a little helps.', 1),
  line('mickey', 'win_small', 2, 'I bank these quietly.', 1),
  line('mickey', 'win_small', 3, 'Little pots fund the big ones.', 1),
  line('mickey', 'lose_big', 0, 'Ah well, the next hand is fresh.', 3, 'sigh'),
  line('mickey', 'lose_big', 1, 'Chips come and chips go here.', 1),
  line('mickey', 'lose_big', 2, 'No use crying over old cards.', 1),
  line('mickey', 'lose_big', 3, 'I have lost bigger and bounced back.', 1),
  line('mickey', 'lose_small', 0, 'Nothing to shrug off really.', 3, 'breath'),
  line('mickey', 'lose_small', 1, 'That one barely registers.', 1),
  line('mickey', 'lose_small', 2, 'Room to breathe, move along.', 1),
  line('mickey', 'lose_small', 3, 'A rounding error, honestly.', 1),
  line('mickey', 'bluff_caught', 0, 'Caught, so it goes here.', 3, 'laugh'),
  line('mickey', 'bluff_caught', 1, 'I tried, you called, well done.', 1),
  line('mickey', 'bluff_caught', 2, 'A bluff is just a risk taken.', 1),
  line('mickey', 'bluff_caught', 3, 'Reads and bluffs, part of the game.', 1),
  line('mickey', 'fold_pressured', 0, 'I fold, no ego about it.', 3, 'breath'),
  line('mickey', 'fold_pressured', 1, 'Smart players know when to go.', 1),
  line('mickey', 'fold_pressured', 2, 'This round is not worth chasing.', 1),
  line('mickey', 'fold_pressured', 3, 'Fold, live to fight on.', 1),
  line('mickey', 'all_in', 0, 'All in, no point sitting still.', 3, 'breath'),
  line('mickey', 'all_in', 1, 'Everything forward right now.', 1),
  line('mickey', 'all_in', 2, 'Commit and let it ride.', 1),
  line('mickey', 'all_in', 3, 'All in, watch this play out.', 1),
  line('mickey', 'raise', 0, 'Raise, keep things moving.', 3, 'scoff'),
  line('mickey', 'raise', 1, 'Bump it up, why not.', 1),
  line('mickey', 'raise', 2, 'A raise to test the room.', 1),
  line('mickey', 'raise', 3, 'I raise, simple as that.', 1),
  line('mickey', 'bad_beat', 0, 'Bad beat, I will survive it.', 3, 'sigh'),
  line('mickey', 'bad_beat', 1, 'Variance again, not even surprised.', 1),
  line('mickey', 'bad_beat', 2, 'Eh, that is how the cards fall.', 1),
  line('mickey', 'bad_beat', 3, 'Shrugged off, I bounce back.', 1),
  line('mickey', 'greeting', 0, 'Evening, friends, take a seat.', 3, 'cheer'),
  line('mickey', 'greeting', 1, 'Hello, good to see you all.', 1),
  line('mickey', 'greeting', 2, 'Another night at the table, good.', 1),
  line('mickey', 'greeting', 3, 'Easy game, enjoy yourselves.', 1),
  line('mickey', 'idle_banter', 0, 'The rooftop crowd never disappoints.', 3, 'breath'),
  line('mickey', 'idle_banter', 1, 'Good music up here tonight.', 1),
  line('mickey', 'idle_banter', 2, 'I have seen wilder tables, believe me.', 1),
  line('mickey', 'idle_banter', 3, 'Friendly table, I like it plenty.', 1),
  line('mickey', 'opponent_stalling', 0, 'All the time in the world here.', 3, 'breath'),
  line('mickey', 'opponent_stalling', 1, 'Take your sweet time, no rush.', 1),
  line('mickey', 'opponent_stalling', 2, 'I am patient, make your choice.', 1),
  line('mickey', 'opponent_stalling', 3, 'Ready when you are, friend.', 1),
]
