/**
 * Turn the measured chair timing into the module the browser imports.
 *
 * The chairs move on tracks authored beside the sit, the leave and the all-in, and the
 * browser owns the chair: the character GLB carries his own motion and nothing else. Rather
 * than transcribe the numbers by hand, this reads what the candidate build measured out of
 * the clips - one offset per frame, in metres, in the character's own frame - and writes it
 * as TypeScript. Regenerate it rather than editing the output.
 *
 * Usage: node art/pipeline/write_seat_timing.mjs <seat-transition-timing.json> <out.ts>
 */
import { readFileSync, writeFileSync } from 'node:fs'

const [source, target] = process.argv.slice(2)
if (source === undefined || target === undefined) {
  console.error('usage: node art/pipeline/write_seat_timing.mjs <timing.json> <out.ts>')
  process.exit(2)
}

const timing = JSON.parse(readFileSync(source, 'utf8'))
const clips = Object.entries(timing.clips ?? {})
if (clips.length === 0) {
  console.error(`${source} carries no clips`)
  process.exit(1)
}

const lines = []
for (const [clip, entry] of clips) {
  const rows = entry.backAway ?? []
  if (rows.length !== entry.lastFrame + 1) {
    console.error(`${clip} has ${rows.length} samples for frames 0 to ${entry.lastFrame}`)
    process.exit(1)
  }
  for (const [index, [frame]] of rows.entries()) {
    if (frame !== index) {
      console.error(`${clip} sample ${index} is frame ${frame}`)
      process.exit(1)
    }
  }
  const values = rows.map(([, metres]) => Number(metres.toFixed(4)))
  lines.push(`  ${clip}: [${values.join(', ')}],`)
}

const body = `/**
 * How far each seat's chair stands back from the table, frame by frame.
 *
 * Generated by art/pipeline/write_seat_timing.mjs from the measured chair tracks beside
 * the sit, the leave and the all-in. Metres in the character's own frame, before the venue
 * scales him: positive is away from the table. Regenerate rather than edit.
 */
export const CHAIR_TRACK_FPS = ${timing.fps}

export const CHAIR_BACK_AWAY: Readonly<Record<string, readonly number[]>> = {
${lines.join('\n')}
}

/** The offset for a clip at a frame, interpolated between samples. */
export function chairBackAway(clip: string, frame: number): number {
  const track = CHAIR_BACK_AWAY[clip]
  if (track === undefined || track.length === 0) return 0
  const clamped = Math.min(track.length - 1, Math.max(0, frame))
  const first = Math.floor(clamped)
  const second = Math.min(track.length - 1, first + 1)
  const mix = clamped - first
  return (track[first] ?? 0) * (1 - mix) + (track[second] ?? 0) * mix
}
`
writeFileSync(target, body)
console.log(`WROTE ${target} from ${clips.length} clips`)
