/**
 * Turn the measured prop places into the module the browser imports.
 *
 * The character GLB carries the man and nothing else, so the chips and the cards a seated
 * player reaches for are the browser's to draw - and it was drawing them somewhere else
 * entirely: a stack a quarter of the way to the middle of the felt, and no hole cards at
 * all. The hands were authored around props whose places were measured in Blender, so this
 * takes those places rather than a guess at them.
 *
 * Blender is Z-up and the character faces -Y; glTF and three.js are Y-up and the import
 * turns (x, y, z) into (x, z, -y), so he faces +Z there. The conversion happens once, here,
 * and the module comes out in the browser's own axes and metres in the character's frame,
 * before the venue scales him.
 *
 * Usage: node art/pipeline/write_seat_props.mjs <seat-prop-places.json> <out.ts>
 *        npx biome check --write <out.ts>   (the tracks come out one frame a line)
 */
import { readFileSync, writeFileSync } from 'node:fs'

const [source, target] = process.argv.slice(2)
if (source === undefined || target === undefined) {
  console.error('usage: node art/pipeline/write_seat_props.mjs <seat-prop-places.json> <out.ts>')
  process.exit(2)
}

const places = JSON.parse(readFileSync(source, 'utf8'))
const round = (value) => Number(value.toFixed(5))

/** Blender (x, y, z) to three.js (x, z, -y). */
function point([x, y, z]) {
  return [round(x), round(z), round(-y)]
}

/**
 * Blender (w, x, y, z) to three.js (x, y, z, w).
 *
 * The axes swap the same way a point's do - the basis change rotates the vector part and
 * leaves the angle alone - and three.js writes the scalar last.
 */
function turn([w, x, y, z]) {
  return [round(x), round(z), round(-y), round(w)]
}

const cards = places.holeCards ?? []
if (cards.length !== 2) {
  console.error(`${source} carries ${cards.length} hole cards, not two`)
  process.exit(1)
}
const lastFrame = places.peekLastFrame
for (const card of cards) {
  if (card.peek.length !== lastFrame + 1) {
    console.error(`${card.action} has ${card.peek.length} samples for frames 0 to ${lastFrame}`)
    process.exit(1)
  }
}

const tracks = cards.map((card) => {
  const rows = card.peek.map((row) => [...point(row.slice(0, 3)), ...turn(row.slice(3))])
  return `  // ${card.action}\n  [\n${rows.map((row) => `    ${row.join(', ')},`).join('\n')}\n  ],`
})

const chip = places.chipStack?.[0]
const allIn = places.allInChips?.[0]
if (chip === undefined || allIn === undefined) {
  console.error(`${source} carries no chip stack`)
  process.exit(1)
}

/** A stack's travel through a clip, one frame a row, as a flat list of x, y, z. */
function travelRows(track, name) {
  if (!Array.isArray(track) || track.length < 2) {
    console.error(`${source} carries no ${name}; re-run read_seat_props.py`)
    process.exit(1)
  }
  return track.map((row) => `  ${point(row).join(', ')},`).join('\n')
}
const pushRows = travelRows(places.chipPushTrack, 'chip push track')
const shoveRows = travelRows(places.allInShoveTrack, 'all-in shove track')

const body = `/**
 * Where a seated player's own chips and cards belong, in his own frame.
 *
 * Generated by art/pipeline/write_seat_props.mjs from the prop tracks measured beside the
 * clips - see art/pipeline/read_seat_props.py. Metres in the character's frame, in three.js
 * axes: +X is his left along the table edge, +Y is up, +Z is towards the middle of the felt.
 * The venue's seat anchor supplies the rest, so a place goes through the anchor's world
 * matrix and lands where his hands were authored to meet it. Regenerate rather than edit.
 *
 * Measured from ${places.source}.
 */

/** The clips and these tracks were authored at one rate; frames below are its frames. */
export const PROP_TRACK_FPS = 30

/**
 * The felt these places were authored on, in the character's own frame.
 *
 * The venue scales him so that this height lands exactly on its own table top - see
 * NATIVE_SILVER_SCALE in art/pipeline/build_assets.py - which is what lets a place measured
 * here be used unchanged. A test holds the two together.
 */
export const AUTHORED_FELT_Y = ${places.proofFeltZ}

/** 63 by 88mm: a playing card, measured off the proof card his hands close on. */
export const HOLE_CARD_SIZE = {
  width: ${places.cardSize.width},
  length: ${places.cardSize.length},
} as const

/** A card's place: position then rotation, both in the character's frame. */
export interface PropPlace {
  position: readonly [number, number, number]
  quaternion: readonly [number, number, number, number]
}

/**
 * The two hole cards through the peek, frame by frame.
 *
 * Seven numbers a frame: x, y, z, then the quaternion as three.js orders it. Frame 0 is
 * where a card lies when it is not being looked at, and the peek returns to it, so the rest
 * place is the first row rather than a second set of numbers that could disagree with it.
 */
export const HOLE_CARD_PEEK: readonly (readonly number[])[] = [
${tracks.join('\n')}
]

/**
 * The frame a held look stops on: the first where both cards are within a millimetre of
 * the top of the lift. Read off the authored track rather than picked, so it moves with it.
 */
export function peekHoldFrame(): number {
  const heights = HOLE_CARD_PEEK.map((track) =>
    Array.from({ length: track.length / 7 }, (_, frame) => track[frame * 7 + 1] ?? 0),
  )
  const tops = heights.map((column) => Math.max(...column))
  const frames = heights[0]?.length ?? 0
  for (let frame = 0; frame < frames; frame += 1) {
    if (heights.every((column, card) => (column[frame] ?? 0) >= (tops[card] ?? 0) - 0.001)) return frame
  }
  return Math.floor(frames / 2)
}

export const PEEK_LAST_FRAME = ${lastFrame}

/**
 * Where a player's own stack sits, and where the chip push sends it.
 *
 * The rest place is what puts the chips under the hand that pushes them. A bet leaves from
 * here and travels with the hand - see CHIP_PUSH_TRACK.
 */
export const CHIP_STACK_PLACE = {
  rest: [${point(chip.rest).join(', ')}] as const,
  pushed: [${point(chip.pushed).join(', ')}] as const,
}

/** The all-in shove starts square in front of him and travels further. */
export const ALL_IN_STACK_PLACE = {
  rest: [${point(allIn.rest).join(', ')}] as const,
  pushed: [${point(allIn.pushed).join(', ')}] as const,
}

/**
 * Where the stack is on every frame of the chip push, three numbers a frame.
 *
 * The hand is not moving for the whole clip - it reaches, pushes and comes back - so chips
 * that slid for the length of it would slide on their own. They move on the frames the
 * stack was authored to move on.
 */
export const CHIP_PUSH_TRACK: readonly number[] = [
${pushRows}
]

/** The same for the all-in shove, whose stack moves late in a clip that is mostly standing up. */
export const ALL_IN_SHOVE_TRACK: readonly number[] = [
${shoveRows}
]

/**
 * How far along its travel a track is at a frame, from 0 before it moves to 1 once it has.
 *
 * Measured along the track's own length, so a chip bet that goes further than the authored
 * stack did still leaves and lands on the hand's beat.
 */
export function travelProgress(track: readonly number[], frame: number): number {
  const frames = track.length / 3 - 1
  if (frames < 1) return 1
  const clamped = Math.min(frames, Math.max(0, frame))
  const at = (index: number): [number, number, number] => [
    track[index * 3] ?? 0,
    track[index * 3 + 1] ?? 0,
    track[index * 3 + 2] ?? 0,
  ]
  const [x0, , z0] = at(0)
  const [x1, , z1] = at(frames)
  const whole = Math.hypot(x1 - x0, z1 - z0)
  if (whole === 0) return 1
  const first = Math.floor(clamped)
  const second = Math.min(frames, first + 1)
  const mix = clamped - first
  const [xa, , za] = at(first)
  const [xb, , zb] = at(second)
  const x = xa * (1 - mix) + xb * mix
  const z = za * (1 - mix) + zb * mix
  // Projected on to the line from start to end, so a track that wobbles sideways still
  // reads as a fraction of the distance covered.
  const along = ((x - x0) * (x1 - x0) + (z - z0) * (z1 - z0)) / (whole * whole)
  return Math.min(1, Math.max(0, along))
}

/** Where a hole card is at a frame of the peek, interpolated between samples. */
export function holeCardAt(card: number, frame: number): PropPlace {
  const track = HOLE_CARD_PEEK[card]
  if (track === undefined || track.length < 7) {
    return { position: [0, 0, 0], quaternion: [0, 0, 0, 1] }
  }
  const frames = track.length / 7 - 1
  const clamped = Math.min(frames, Math.max(0, frame))
  const first = Math.floor(clamped) * 7
  const second = Math.min(frames * 7, first + 7)
  const mix = clamped - Math.floor(clamped)
  const at = (index: number, offset: number) => track[index + offset] ?? 0
  // Nearly a slerp: adjacent samples are a thirtieth of a second apart, so the shortest arc
  // between them is small and a normalised lerp is within a fraction of a degree of it. The
  // sign check is not optional - a quaternion and its negative are the same rotation, and
  // lerping across that sign takes the card the long way round.
  const flip = [3, 4, 5, 6].reduce((sum, offset) => sum + at(first, offset) * at(second, offset), 0) < 0 ? -1 : 1
  const turn: number[] = []
  for (const offset of [3, 4, 5, 6]) {
    turn.push(at(first, offset) * (1 - mix) + at(second, offset) * flip * mix)
  }
  const length = Math.hypot(turn[0] ?? 0, turn[1] ?? 0, turn[2] ?? 0, turn[3] ?? 0) || 1
  return {
    position: [
      at(first, 0) * (1 - mix) + at(second, 0) * mix,
      at(first, 1) * (1 - mix) + at(second, 1) * mix,
      at(first, 2) * (1 - mix) + at(second, 2) * mix,
    ],
    quaternion: [
      (turn[0] ?? 0) / length,
      (turn[1] ?? 0) / length,
      (turn[2] ?? 0) / length,
      (turn[3] ?? 1) / length,
    ],
  }
}
`
writeFileSync(target, body)
console.log(
  `WROTE ${target} from ${cards.length} card tracks, a ${places.chipStack.length} chip stack and two travel tracks`,
)
