/**
 * Where a seated player's own chips and cards belong, in his own frame.
 *
 * Generated by art/pipeline/write_seat_props.mjs from the prop tracks measured beside the
 * clips - see art/pipeline/read_seat_props.py. Metres in the character's frame, in three.js
 * axes: +X is his left along the table edge, +Y is up, +Z is towards the middle of the felt.
 * The venue's seat anchor supplies the rest, so a place goes through the anchor's world
 * matrix and lands where his hands were authored to meet it. Regenerate rather than edit.
 *
 * Measured from silver-integration-candidate.blend.
 */

/** The clips and these tracks were authored at one rate; frames below are its frames. */
export const PROP_TRACK_FPS = 30

/**
 * The felt these places were authored on, in the character's own frame.
 *
 * The venue scales him so that this height lands exactly on its own table top - see
 * NATIVE_SILVER_SCALE in art/pipeline/build_assets.py - which is what lets a place measured
 * here be used unchanged. A test holds the two together.
 */
export const AUTHORED_FELT_Y = 0.7935

/** 63 by 88mm: a playing card, measured off the proof card his hands close on. */
export const HOLE_CARD_SIZE = {
  width: 0.063,
  length: 0.088,
} as const

/** A card's place: position then rotation, both in the character's frame. */
export interface PropPlace {
  position: readonly [number, number, number]
  quaternion: readonly [number, number, number, number]
}

/**
 * The two hole cards through the peek, frame by frame.
 *
 * Seven numbers a frame: x, y, z, then the quaternion as three.js orders it. Frame 0 is
 * where a card lies when it is not being looked at, and the peek returns to it, so the rest
 * place is the first row rather than a second set of numbers that could disagree with it.
 */
export const HOLE_CARD_PEEK: readonly (readonly number[])[] = [
  // A44d proof card motion 0
  [
    0.03195, 0.7942, 0.44712, 0, 0, 0, 1, 0.03195, 0.7942, 0.44712, 0, 0, 0, 1, 0.03195, 0.7942,
    0.44712, 0, 0, 0, 1, 0.03195, 0.7942, 0.44712, 0, 0, 0, 1, 0.03195, 0.7942, 0.44712, 0, 0, 0, 1,
    0.03195, 0.7942, 0.44712, 0, 0, 0, 1, 0.03195, 0.7942, 0.44712, 0, 0, 0, 1, 0.03195, 0.7942,
    0.44712, 0, 0, 0, 1, 0.03218, 0.79594, 0.44955, 0, 0, 0, 1, 0.03243, 0.79762, 0.45202, 0, 0, 0,
    1, 0.03269, 0.79858, 0.45458, 0, 0, 0, 1, 0.033, 0.79799, 0.45722, 0, 0, 0, 1, 0.03338, 0.79675,
    0.45951, 0, 0, 0, 1, 0.03387, 0.79352, 0.4635, 0, 0, 0, 1, 0.03436, 0.8001, 0.46591, 0.07473, 0,
    0, 0.9972, 0.01688, 0.81394, 0.47156, 0.17239, 0.22501, -0.09878, 0.95388, 0.02132, 0.82358,
    0.45989, 0.33258, 0.33181, -0.12231, 0.87426, -0.00447, 0.84725, 0.45292, 0.51211, 0.31947,
    -0.17934, 0.77687, 0.00543, 0.87072, 0.44025, 0.55837, 0.31055, -0.20431, 0.74165, 0.00777,
    0.88455, 0.43592, 0.58888, 0.39869, -0.25242, 0.65617, 0.01439, 0.88939, 0.43416, 0.60386,
    0.40649, -0.13248, 0.67273, 0.01439, 0.88939, 0.43416, 0.60386, 0.40649, -0.13248, 0.67273,
    0.01439, 0.88939, 0.43416, 0.60386, 0.40649, -0.13248, 0.67273, 0.01439, 0.88939, 0.43416,
    0.60386, 0.40649, -0.13248, 0.67273, 0.01439, 0.88939, 0.43416, 0.60386, 0.40649, -0.13248,
    0.67273, 0.01439, 0.88939, 0.43416, 0.60386, 0.40649, -0.13248, 0.67273, 0.01439, 0.88939,
    0.43416, 0.60386, 0.40649, -0.13248, 0.67273, 0.01439, 0.88939, 0.43416, 0.60386, 0.40649,
    -0.13248, 0.67273, 0.01402, 0.88281, 0.43688, 0.60386, 0.40649, -0.13248, 0.67273, 0.02015,
    0.87174, 0.44155, 0.46578, 0.50161, -0.09853, 0.7223, 0.02223, 0.85332, 0.44527, 0.37846,
    0.58215, -0.06133, 0.71701, 0.01964, 0.83339, 0.45021, 0.33767, 0.58805, 0.00433, 0.73495,
    0.01187, 0.81555, 0.45703, 0.24446, 0.55748, 0.00768, 0.79335, 0.03453, 0.79987, 0.46603,
    0.07473, 0, 0, 0.9972, 0.03387, 0.79332, 0.4635, 0, 0, 0, 1, 0.03337, 0.79672, 0.45991, 0, 0, 0,
    1, 0.03295, 0.79815, 0.45802, 0, 0, 0, 1, 0.03261, 0.79896, 0.45574, 0, 0, 0, 1, 0.03235,
    0.79849, 0.45351, 0, 0, 0, 1, 0.03217, 0.79713, 0.45134, 0, 0, 0, 1, 0.03204, 0.79568, 0.44922,
    0, 0, 0, 1, 0.03195, 0.7942, 0.44712, 0, 0, 0, 1, 0.03195, 0.7942, 0.44712, 0, 0, 0, 1, 0.03195,
    0.7942, 0.44712, 0, 0, 0, 1, 0.03195, 0.7942, 0.44712, 0, 0, 0, 1, 0.03195, 0.7942, 0.44712, 0,
    0, 0, 1, 0.03195, 0.7942, 0.44712, 0, 0, 0, 1, 0.03195, 0.7942, 0.44712, 0, 0, 0, 1, 0.03195,
    0.7942, 0.44712, 0, 0, 0, 1,
  ],
  // A44d proof card motion 1
  [
    0.04595, 0.7947, 0.44712, 0, 0.10453, 0, 0.99452, 0.04595, 0.7947, 0.44712, 0, 0.10453, 0,
    0.99452, 0.04595, 0.7947, 0.44712, 0, 0.10453, 0, 0.99452, 0.04595, 0.7947, 0.44712, 0, 0.10453,
    0, 0.99452, 0.04595, 0.7947, 0.44712, 0, 0.10453, 0, 0.99452, 0.04595, 0.7947, 0.44712, 0,
    0.10453, 0, 0.99452, 0.04595, 0.7947, 0.44712, 0, 0.10453, 0, 0.99452, 0.04595, 0.7947, 0.44712,
    0, 0.10453, 0, 0.99452, 0.04618, 0.79644, 0.44955, 0, 0.10453, 0, 0.99452, 0.04643, 0.79812,
    0.45202, 0, 0.10453, 0, 0.99452, 0.04669, 0.79908, 0.45458, 0, 0.10453, 0, 0.99452, 0.047,
    0.79849, 0.45722, 0, 0.10453, 0, 0.99452, 0.04738, 0.79725, 0.45951, 0, 0.10453, 0, 0.99452,
    0.04787, 0.79402, 0.4635, 0, 0.10453, 0, 0.99452, 0.04836, 0.80059, 0.46599, 0.07432, 0.10424,
    0.00781, 0.99174, 0.02932, 0.81285, 0.46522, 0.18177, 0.32349, -0.08022, 0.92514, 0.03203,
    0.82405, 0.45088, 0.34354, 0.42138, -0.08688, 0.83479, 0.00608, 0.84813, 0.44374, 0.52805,
    0.39892, -0.12483, 0.73922, 0.01588, 0.87148, 0.43096, 0.57667, 0.38637, -0.14483, 0.70512,
    0.01593, 0.88657, 0.42472, 0.61203, 0.46509, -0.18948, 0.6109, 0.0236, 0.89389, 0.42462, 0.6144,
    0.47458, -0.06864, 0.62656, 0.0236, 0.89389, 0.42462, 0.6144, 0.47458, -0.06864, 0.62656,
    0.0236, 0.89389, 0.42462, 0.6144, 0.47458, -0.06864, 0.62656, 0.0236, 0.89389, 0.42462, 0.6144,
    0.47458, -0.06864, 0.62656, 0.0236, 0.89389, 0.42462, 0.6144, 0.47458, -0.06864, 0.62656,
    0.0236, 0.89389, 0.42462, 0.6144, 0.47458, -0.06864, 0.62656, 0.0236, 0.89389, 0.42462, 0.6144,
    0.47458, -0.06864, 0.62656, 0.0236, 0.89389, 0.42462, 0.6144, 0.47458, -0.06864, 0.62656,
    0.02323, 0.8873, 0.42734, 0.6144, 0.47458, -0.06864, 0.62656, 0.02714, 0.87656, 0.4304, 0.47353,
    0.57436, -0.04931, 0.66591, 0.0269, 0.85861, 0.43317, 0.3828, 0.65391, -0.02143, 0.65224,
    0.02415, 0.83942, 0.4384, 0.33537, 0.66166, 0.03961, 0.66946, 0.0173, 0.81997, 0.4449, 0.24232,
    0.63735, 0.03319, 0.73073, 0.04853, 0.80036, 0.46611, 0.07432, 0.10424, 0.00781, 0.99174,
    0.04787, 0.79382, 0.4635, 0, 0.10453, 0, 0.99452, 0.04737, 0.79722, 0.45991, 0, 0.10453, 0,
    0.99452, 0.04695, 0.79865, 0.45802, 0, 0.10453, 0, 0.99452, 0.04661, 0.79946, 0.45574, 0,
    0.10453, 0, 0.99452, 0.04635, 0.79899, 0.45351, 0, 0.10453, 0, 0.99452, 0.04617, 0.79763,
    0.45134, 0, 0.10453, 0, 0.99452, 0.04604, 0.79618, 0.44922, 0, 0.10453, 0, 0.99452, 0.04595,
    0.7947, 0.44712, 0, 0.10453, 0, 0.99452, 0.04595, 0.7947, 0.44712, 0, 0.10453, 0, 0.99452,
    0.04595, 0.7947, 0.44712, 0, 0.10453, 0, 0.99452, 0.04595, 0.7947, 0.44712, 0, 0.10453, 0,
    0.99452, 0.04595, 0.7947, 0.44712, 0, 0.10453, 0, 0.99452, 0.04595, 0.7947, 0.44712, 0, 0.10453,
    0, 0.99452, 0.04595, 0.7947, 0.44712, 0, 0.10453, 0, 0.99452, 0.04595, 0.7947, 0.44712, 0,
    0.10453, 0, 0.99452,
  ],
]

/**
 * The frame a held look stops on: the first where both cards are within a millimetre of
 * the top of the lift. Read off the authored track rather than picked, so it moves with it.
 */
export function peekHoldFrame(): number {
  const heights = HOLE_CARD_PEEK.map((track) =>
    Array.from({ length: track.length / 7 }, (_, frame) => track[frame * 7 + 1] ?? 0),
  )
  const tops = heights.map((column) => Math.max(...column))
  const frames = heights[0]?.length ?? 0
  for (let frame = 0; frame < frames; frame += 1) {
    if (heights.every((column, card) => (column[frame] ?? 0) >= (tops[card] ?? 0) - 0.001))
      return frame
  }
  return Math.floor(frames / 2)
}

export const PEEK_LAST_FRAME = 48

/**
 * Where a player's own stack sits, and where the chip push sends it.
 *
 * The rest place is what puts the chips under the hand that pushes them. A bet leaves from
 * here and travels with the hand - see CHIP_PUSH_TRACK.
 */
export const CHIP_STACK_PLACE = {
  rest: [0.035, 0.79517, 0.5] as const,
  pushed: [-0.001, 0.79517, 0.602] as const,
}

/** The all-in shove starts square in front of him and travels further. */
export const ALL_IN_STACK_PLACE = {
  rest: [0, 0.79517, 0.5] as const,
  pushed: [0, 0.79517, 0.63] as const,
}

/**
 * Where the stack is on every frame of the chip push, three numbers a frame.
 *
 * The hand is not moving for the whole clip - it reaches, pushes and comes back - so chips
 * that slid for the length of it would slide on their own. They move on the frames the
 * stack was authored to move on.
 */
export const CHIP_PUSH_TRACK: readonly number[] = [
  0.035, 0.79517, 0.5, 0.035, 0.79517, 0.5, 0.035, 0.79517, 0.5, 0.035, 0.79517, 0.5, 0.035,
  0.79517, 0.5, 0.035, 0.79517, 0.5, 0.03377, 0.79517, 0.5035, 0.03046, 0.79517, 0.51287, 0.02567,
  0.79517, 0.52644, 0.01999, 0.79517, 0.54254, 0.01401, 0.79517, 0.55947, 0.00833, 0.79517, 0.57556,
  0.00354, 0.79517, 0.58913, 0.00023, 0.79517, 0.5985, -0.001, 0.79517, 0.602, -0.001, 0.79517,
  0.602, -0.001, 0.79517, 0.602, -0.001, 0.79517, 0.602, -0.001, 0.79517, 0.602, -0.001, 0.79517,
  0.602, -0.001, 0.79517, 0.602, -0.001, 0.79517, 0.602, -0.001, 0.79517, 0.602, -0.001, 0.79517,
  0.602, -0.001, 0.79517, 0.602, -0.001, 0.79517, 0.602, -0.001, 0.79517, 0.602, -0.001, 0.79517,
  0.602, -0.001, 0.79517, 0.602, -0.001, 0.79517, 0.602, -0.001, 0.79517, 0.602,
]

/** The same for the all-in shove, whose stack moves late in a clip that is mostly standing up. */
export const ALL_IN_SHOVE_TRACK: readonly number[] = [
  0, 0.79517, 0.5, 0, 0.79517, 0.5, 0, 0.79517, 0.5, 0, 0.79517, 0.5, 0, 0.79517, 0.5, 0, 0.79517,
  0.5, 0, 0.79517, 0.5, 0, 0.79517, 0.5, 0, 0.79517, 0.5, 0, 0.79517, 0.5, 0, 0.79517, 0.5, 0,
  0.79517, 0.5, 0, 0.79517, 0.5, 0, 0.79517, 0.5, 0, 0.79517, 0.5, 0, 0.79517, 0.5, 0, 0.79517, 0.5,
  0, 0.79517, 0.50559, 0, 0.79517, 0.52031, 0, 0.79517, 0.54113, 0, 0.79517, 0.565, 0, 0.79517,
  0.58887, 0, 0.79517, 0.60969, 0, 0.79517, 0.62441, 0, 0.79517, 0.63, 0, 0.79517, 0.63, 0, 0.79517,
  0.63, 0, 0.79517, 0.63, 0, 0.79517, 0.63, 0, 0.79517, 0.63, 0, 0.79517, 0.63, 0, 0.79517, 0.63, 0,
  0.79517, 0.63, 0, 0.79517, 0.63, 0, 0.79517, 0.63, 0, 0.79517, 0.63, 0, 0.79517, 0.63, 0, 0.79517,
  0.63, 0, 0.79517, 0.63, 0, 0.79517, 0.63, 0, 0.79517, 0.63, 0, 0.79517, 0.63, 0, 0.79517, 0.63, 0,
  0.79517, 0.63, 0, 0.79517, 0.63, 0, 0.79517, 0.63, 0, 0.79517, 0.63, 0, 0.79517, 0.63, 0, 0.79517,
  0.63, 0, 0.79517, 0.63, 0, 0.79517, 0.63, 0, 0.79517, 0.63, 0, 0.79517, 0.63, 0, 0.79517, 0.63, 0,
  0.79517, 0.63, 0, 0.79517, 0.63, 0, 0.79517, 0.63, 0, 0.79517, 0.63, 0, 0.79517, 0.63, 0, 0.79517,
  0.63, 0, 0.79517, 0.63, 0, 0.79517, 0.63, 0, 0.79517, 0.63, 0, 0.79517, 0.63, 0, 0.79517, 0.63, 0,
  0.79517, 0.63, 0, 0.79517, 0.63, 0, 0.79517, 0.63, 0, 0.79517, 0.63, 0, 0.79517, 0.63, 0, 0.79517,
  0.63, 0, 0.79517, 0.63, 0, 0.79517, 0.63, 0, 0.79517, 0.63, 0, 0.79517, 0.63, 0, 0.79517, 0.63, 0,
  0.79517, 0.63, 0, 0.79517, 0.63, 0, 0.79517, 0.63, 0, 0.79517, 0.63, 0, 0.79517, 0.63, 0, 0.79517,
  0.63, 0, 0.79517, 0.63, 0, 0.79517, 0.63, 0, 0.79517, 0.63, 0, 0.79517, 0.63, 0, 0.79517, 0.63, 0,
  0.79517, 0.63, 0, 0.79517, 0.63, 0, 0.79517, 0.63, 0, 0.79517, 0.63,
]

/**
 * How far along its travel a track is at a frame, from 0 before it moves to 1 once it has.
 *
 * Measured along the track's own length, so a chip bet that goes further than the authored
 * stack did still leaves and lands on the hand's beat.
 */
export function travelProgress(track: readonly number[], frame: number): number {
  const frames = track.length / 3 - 1
  if (frames < 1) return 1
  const clamped = Math.min(frames, Math.max(0, frame))
  const at = (index: number): [number, number, number] => [
    track[index * 3] ?? 0,
    track[index * 3 + 1] ?? 0,
    track[index * 3 + 2] ?? 0,
  ]
  const [x0, , z0] = at(0)
  const [x1, , z1] = at(frames)
  const whole = Math.hypot(x1 - x0, z1 - z0)
  if (whole === 0) return 1
  const first = Math.floor(clamped)
  const second = Math.min(frames, first + 1)
  const mix = clamped - first
  const [xa, , za] = at(first)
  const [xb, , zb] = at(second)
  const x = xa * (1 - mix) + xb * mix
  const z = za * (1 - mix) + zb * mix
  // Projected on to the line from start to end, so a track that wobbles sideways still
  // reads as a fraction of the distance covered.
  const along = ((x - x0) * (x1 - x0) + (z - z0) * (z1 - z0)) / (whole * whole)
  return Math.min(1, Math.max(0, along))
}

/** Where a hole card is at a frame of the peek, interpolated between samples. */
export function holeCardAt(card: number, frame: number): PropPlace {
  const track = HOLE_CARD_PEEK[card]
  if (track === undefined || track.length < 7) {
    return { position: [0, 0, 0], quaternion: [0, 0, 0, 1] }
  }
  const frames = track.length / 7 - 1
  const clamped = Math.min(frames, Math.max(0, frame))
  const first = Math.floor(clamped) * 7
  const second = Math.min(frames * 7, first + 7)
  const mix = clamped - Math.floor(clamped)
  const at = (index: number, offset: number) => track[index + offset] ?? 0
  // Nearly a slerp: adjacent samples are a thirtieth of a second apart, so the shortest arc
  // between them is small and a normalised lerp is within a fraction of a degree of it. The
  // sign check is not optional - a quaternion and its negative are the same rotation, and
  // lerping across that sign takes the card the long way round.
  const flip =
    [3, 4, 5, 6].reduce((sum, offset) => sum + at(first, offset) * at(second, offset), 0) < 0
      ? -1
      : 1
  const turn: number[] = []
  for (const offset of [3, 4, 5, 6]) {
    turn.push(at(first, offset) * (1 - mix) + at(second, offset) * flip * mix)
  }
  const length = Math.hypot(turn[0] ?? 0, turn[1] ?? 0, turn[2] ?? 0, turn[3] ?? 0) || 1
  return {
    position: [
      at(first, 0) * (1 - mix) + at(second, 0) * mix,
      at(first, 1) * (1 - mix) + at(second, 1) * mix,
      at(first, 2) * (1 - mix) + at(second, 2) * mix,
    ],
    quaternion: [
      (turn[0] ?? 0) / length,
      (turn[1] ?? 0) / length,
      (turn[2] ?? 0) / length,
      (turn[3] ?? 1) / length,
    ],
  }
}
